export const SWITCH_RESULT_CURRENCY = 'SWITCH_RESULT_CURRENCY';
export const ADD_CURRENCY = 'ADD_CURRENCY';
export const CALCULATION_SUCCESS = 'CALCULATION_SUCCESS';
export const RESET_CALCULATION = 'RESET_CALCULATION';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
